// Code generated by Falak (the Go function runtime). DO NOT EDIT.
//
// falak-fn-install copies this file into the function's package (package main) next to a generated main(). It
// serves the function's Handler on $PORT, runs its Scheduled handler for `falak-fn-run`, and reports telemetry to
// $FALAK_OTLP_SOCKET following the Falak telemetry contract (contracts/telemetry/README.md), encoded like the other
// runtimes: request spans named by the ServeMux pattern, panics, outgoing HTTP calls and scheduled runs. Standard
// library only. Identifiers starting with "falak" and the Event type are reserved for it.

package main

import (
	"bufio"
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/signal"
	"regexp"
	"runtime"
	"runtime/debug"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"time"
)

// Event is what Scheduled receives: which schedule fired, and why.
type Event struct {
	// Name of the schedule ("Hourly").
	Name string `json:"name"`
	// Schedule is its key.
	Schedule string `json:"schedule"`
	// Cron is its expression ("@hourly", "*/5 * * * *").
	Cron string `json:"cron"`
	// Trigger is "cron", or "manual" for Run now.
	Trigger string `json:"trigger"`
	// ScheduledTime is when the run started.
	ScheduledTime time.Time `json:"scheduled_time"`
}

// falakAdapt accepts what a function may export as Handler: an http.Handler (a *http.ServeMux, a router) or a
// func(http.ResponseWriter, *http.Request).
func falakAdapt(h any) http.Handler {
	switch v := h.(type) {
	case http.Handler:
		return v
	case func(http.ResponseWriter, *http.Request):
		return http.HandlerFunc(v)
	}
	panic(fmt.Sprintf("falak: Handler must be an http.Handler or a func(http.ResponseWriter, *http.Request), not %T", h))
}

// falakMain is the generated main(): `run` runs Scheduled once, anything else serves Handler.
func falakMain(handler http.Handler, scheduled func(context.Context, Event) error) {
	falakInstrumentHTTP()
	if len(os.Args) > 1 && os.Args[1] == "run" {
		os.Exit(falakRun(scheduled))
	}
	falakServe(handler)
}

func falakServe(handler http.Handler) {
	if handler == nil {
		handler = http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			http.Error(w, "this function has no Handler (it only runs on schedules)", http.StatusNotFound)
		})
	}
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
	srv := &http.Server{Addr: "0.0.0.0:" + port, Handler: falakTrace(handler), ReadHeaderTimeout: 30 * time.Second}

	stop := make(chan os.Signal, 1)
	signal.Notify(stop, syscall.SIGTERM, syscall.SIGINT)
	done := make(chan struct{})
	go func() {
		<-stop
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		_ = srv.Shutdown(ctx)
		close(done)
	}()

	// Package init (the function's globals) has run: listening now means ready.
	if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
		fmt.Fprintln(os.Stderr, "falak:", err)
		os.Exit(1)
	}
	<-done
	falakTelemetry.flush()
}

func falakRun(scheduled func(context.Context, Event) error) (code int) {
	name := os.Getenv("FALAK_SCHEDULE_NAME")
	if name == "" {
		name = os.Getenv("FALAK_SCHEDULE")
	}
	event := Event{Name: name, Schedule: os.Getenv("FALAK_SCHEDULE"), Cron: os.Getenv("FALAK_SCHEDULE_CRON"), Trigger: "cron", ScheduledTime: time.Now()}
	if os.Getenv("FALAK_TRIGGER") == "manual" {
		event.Trigger = "manual"
	}
	if scheduled == nil {
		fmt.Fprintln(os.Stderr, "falak: the function has no Scheduled handler: add `func Scheduled(ctx context.Context, event Event) error`")
		return 1
	}

	ctx, cancel := signal.NotifyContext(context.Background(), syscall.SIGTERM, syscall.SIGINT)
	defer cancel()
	cron := ""
	if event.Cron != "" {
		cron = ", " + event.Cron
	}
	fmt.Printf("falak: running %s (%s%s)\n", name, event.Trigger, cron)
	span := falakNewSpan("schedule "+name, falakInternal, nil,
		falakStr("falak.event.type", "scheduled_task"), falakStr("falak.schedule.name", name), falakStr("falak.schedule.expression", event.Cron))
	started := time.Now()

	err := func() (err error) {
		defer func() {
			if v := recover(); v != nil {
				err = &falakPanic{value: v, stack: debug.Stack()}
			}
		}()
		return scheduled(falakWithSpan(ctx, span), event)
	}()

	if err != nil {
		code = 1
		fmt.Fprintf(os.Stderr, "falak: %s failed: %v\n", name, err)
		var p *falakPanic
		if errors.As(err, &p) {
			os.Stderr.Write(p.stack)
		}
		span.exception(err, false)
		span.attr(falakStr("falak.schedule.status", "failed"))
	} else {
		fmt.Printf("falak: %s finished in %dms\n", name, time.Since(started).Milliseconds())
		span.attr(falakStr("falak.schedule.status", "finished"))
	}
	falakTelemetry.finish(span)
	falakTelemetry.flush()
	return code
}

// ---- requests -----------------------------------------------------------------------------------------------------

const falakUnmatched = "(unmatched)"

var falakSegment = regexp.MustCompile(`(?i)^\d+$|^[0-9a-f-]{16,}$|^[A-Za-z0-9_-]{24,}$`)

// falakNormalize: /users/42 → /users/:id, for handlers without a ServeMux pattern.
func falakNormalize(path string) string {
	segs := strings.Split(path, "/")
	for i, s := range segs {
		if falakSegment.MatchString(s) {
			segs[i] = ":id"
		}
	}
	if out := strings.Join(segs, "/"); out != "" {
		return out
	}
	return "/"
}

// falakRoute is the route template the ServeMux matched ("GET /users/{id}" → "/users/{id}", "GET /{$}" → "/"),
// else "".
func falakRoute(pattern string) string {
	if i := strings.IndexByte(pattern, '/'); i >= 0 {
		return strings.TrimSuffix(pattern[i:], "{$}")
	}
	return ""
}

var falakTraceparent = regexp.MustCompile(`^00-([0-9a-f]{32})-([0-9a-f]{16})-[0-9a-f]{2}$`)

// falakTrace wraps the function's handler: one `request` span per request, panics recorded (answered with 500).
func falakTrace(h http.Handler) http.Handler {
	_, isMux := h.(*http.ServeMux)
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !falakTelemetry.enabled {
			falakServeSafely(h, w, r, nil)
			return
		}
		span := falakNewSpan(r.Method, falakServer, nil,
			falakStr("falak.event.type", "request"), falakStr("http.request.method", r.Method), falakStr("url.path", falakRedactPath(r.URL.Path)),
			falakBool("faas.coldstart", r.Header.Get("X-Falak-Cold-Start") == "1"))
		if m := falakTraceparent.FindStringSubmatch(r.Header.Get("traceparent")); m != nil {
			span.TraceID, span.ParentSpanID = m[1], m[2]
		}
		rec := &falakRecorder{ResponseWriter: w}
		req := r.WithContext(falakWithSpan(r.Context(), span))
		falakServeSafely(h, rec, req, span)

		route := falakRoute(req.Pattern)
		switch {
		case route != "":
		case isMux:
			route = falakUnmatched
		default:
			route = falakRedactPath(falakNormalize(r.URL.Path))
		}
		status := rec.status
		if status == 0 {
			status = http.StatusOK
		}
		span.Name = r.Method + " " + route
		span.attr(falakStr("http.route", route), falakInt("http.response.status_code", int64(status)))
		if status >= 500 && span.Status == nil {
			span.Status = &falakStatus{Code: falakError}
		}
		falakTelemetry.finish(span)
	})
}

// falakServeSafely turns a panic into a 500 (and an exception on the span) instead of a dropped connection.
func falakServeSafely(h http.Handler, w http.ResponseWriter, r *http.Request, span *falakSpan) {
	defer func() {
		v := recover()
		if v == nil {
			return
		}
		if v == http.ErrAbortHandler {
			panic(v)
		}
		p := &falakPanic{value: v, stack: debug.Stack()}
		fmt.Fprintf(os.Stderr, "falak: panic serving %s %s: %v\n%s", r.Method, r.URL.Path, v, p.stack)
		if span != nil {
			span.exception(p, false)
		}
		if rec, ok := w.(*falakRecorder); !ok || rec.status == 0 {
			http.Error(w, "Internal Server Error", http.StatusInternalServerError)
		}
	}()
	h.ServeHTTP(w, r)
}

type falakPanic struct {
	value any
	stack []byte
}

func (p *falakPanic) Error() string { return fmt.Sprint(p.value) }

// falakRecorder notes the status; Unwrap keeps http.ResponseController (flush, deadlines, hijack) working.
type falakRecorder struct {
	http.ResponseWriter
	status int
}

func (r *falakRecorder) WriteHeader(code int) {
	if r.status == 0 {
		r.status = code
	}
	r.ResponseWriter.WriteHeader(code)
}

func (r *falakRecorder) Write(b []byte) (int, error) {
	if r.status == 0 {
		r.status = http.StatusOK
	}
	return r.ResponseWriter.Write(b)
}

func (r *falakRecorder) Unwrap() http.ResponseWriter { return r.ResponseWriter }

// Flush, Hijack and ReadFrom pass through to the server's writer, so libraries that type-assert it (websockets,
// streaming, sendfile) work as without Falak.
func (r *falakRecorder) Flush() {
	if f, ok := r.ResponseWriter.(http.Flusher); ok {
		if r.status == 0 {
			r.status = http.StatusOK
		}
		f.Flush()
	}
}

func (r *falakRecorder) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	h, ok := r.ResponseWriter.(http.Hijacker)
	if !ok {
		return nil, nil, http.ErrNotSupported
	}
	conn, rw, err := h.Hijack()
	if err == nil && r.status == 0 {
		r.status = http.StatusSwitchingProtocols
	}
	return conn, rw, err
}

func (r *falakRecorder) ReadFrom(src io.Reader) (int64, error) {
	if r.status == 0 {
		r.status = http.StatusOK
	}
	if rf, ok := r.ResponseWriter.(io.ReaderFrom); ok {
		return rf.ReadFrom(src)
	}
	return io.Copy(struct{ io.Writer }{r.ResponseWriter}, src)
}

// ---- outgoing HTTP ------------------------------------------------------------------------------------------------

// falakInstrumentHTTP traces http.DefaultClient (http.Get, http.Post, http.DefaultClient.Do). http.DefaultTransport
// itself stays an *http.Transport, so code that clones it (`http.DefaultTransport.(*http.Transport).Clone()`)
// keeps working; a client of your own is traced with `Transport: http.DefaultClient.Transport`.
func falakInstrumentHTTP() {
	base := http.DefaultClient.Transport
	if base == nil {
		base = http.DefaultTransport
	}
	http.DefaultClient.Transport = &falakTransport{base: base}
}

// falakTransport records `outgoing_request` spans for calls made with a request's (or a run's) context:
// http.NewRequestWithContext(r.Context(), …) or the ctx Scheduled receives. No query strings or userinfo, and secret
// path segments are redacted (falakRedactPath).
type falakTransport struct{ base http.RoundTripper }

func (t *falakTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	parent := falakSpanFrom(req.Context())
	if parent == nil || !falakTelemetry.enabled {
		return t.base.RoundTrip(req)
	}
	span := falakNewSpan(req.Method+" "+req.URL.Host, falakClient, parent,
		falakStr("falak.event.type", "outgoing_request"), falakStr("http.request.method", req.Method),
		falakStr("url.full", falakSafeURL(req.URL)), falakStr("server.address", req.URL.Hostname()))
	res, err := t.base.RoundTrip(req)
	if err != nil {
		span.exception(err, true)
		span.Status = &falakStatus{Code: falakError, Message: falakCut(falakRedactText(err.Error()), 512)}
	} else {
		span.attr(falakInt("http.response.status_code", int64(res.StatusCode)))
		if res.StatusCode >= 500 {
			span.Status = &falakStatus{Code: falakError}
		}
	}
	falakTelemetry.finish(span)
	return res, err
}

// ---- redaction ---------------------------------------------------------------------------------------------------

// Secrets in URL paths never reach telemetry: the same rules as the other runtimes (shared/redact.mjs) and the
// function gateway.
const falakRedacted = "{redacted}"

var (
	falakTelegram   = regexp.MustCompile(`^bot\d+:[A-Za-z0-9_-]+$`)
	falakColonToken = regexp.MustCompile(`^[A-Za-z0-9_-]+:[A-Za-z0-9_-]{16,}$`)
	falakLong       = regexp.MustCompile(`^[A-Za-z0-9_:-]{32,}$`)
	falakMixed      = regexp.MustCompile(`^[A-Za-z0-9_-]{20,}$`)
	falakEscape     = regexp.MustCompile(`%[0-9A-Fa-f]{2}`)
	falakAbsolute   = regexp.MustCompile(`^([a-zA-Z][a-zA-Z0-9+.-]*)://([^?#]*)`)
)

func falakClassify(seg string) string {
	digit := strings.ContainsAny(seg, "0123456789")
	switch {
	case falakTelegram.MatchString(seg):
		return "bot" + falakRedacted
	case falakColonToken.MatchString(seg), falakLong.MatchString(seg) && digit:
		return falakRedacted
	case falakMixed.MatchString(seg) && digit && strings.ToLower(seg) != seg && strings.ToUpper(seg) != seg:
		return falakRedacted
	}
	return seg
}

// falakUnescape decodes percent-escapes (a few rounds, for double encoding); malformed escapes are left as they are.
func falakUnescape(seg string) string {
	for i := 0; i < 3 && strings.Contains(seg, "%"); i++ {
		next := falakEscape.ReplaceAllStringFunc(seg, func(e string) string {
			b, _ := strconv.ParseUint(e[1:], 16, 8)
			return string(rune(b))
		})
		if next == seg {
			break
		}
		seg = next
	}
	return seg
}

// falakRedactSegment returns one path segment, or {redacted} when it looks like a secret. Escaped segments are
// judged decoded (bot123%3Aabc is bot123:abc), and kept as written when they are harmless.
func falakRedactSegment(seg string) string {
	plain := falakUnescape(seg)
	if plain == seg {
		return falakClassify(seg)
	}
	if verdict := falakClassify(plain); verdict != plain {
		return verdict
	}
	for _, part := range strings.Split(plain, "/") {
		if falakClassify(part) != part {
			return falakRedacted
		}
	}
	return seg
}

// falakRedactPath: /bot123:AAE…/sendMessage → /bot{redacted}/sendMessage.
func falakRedactPath(p string) string {
	segs := strings.Split(p, "/")
	for i, s := range segs {
		segs[i] = falakRedactSegment(s)
	}
	return strings.Join(segs, "/")
}

// falakSafeURL is scheme://host[:port]/path: no userinfo, no query, no fragment, secret segments redacted.
func falakSafeURL(u *url.URL) string {
	// EscapedPath encodes the braces of a placeholder already in the URL (error texts): keep it readable.
	p := strings.ReplaceAll(u.EscapedPath(), "%7Bredacted%7D", falakRedacted)
	if p == "" {
		p = "/"
	}
	return u.Scheme + "://" + u.Host + falakRedactPath(p)
}

var falakURLInText = regexp.MustCompile(`[a-zA-Z][a-zA-Z0-9+.-]*://[^\s"'<>` + "`" + `]+`)

// falakRedactText makes every URL a free text quotes safe (Go's errors quote the full request URL).
func falakRedactText(s string) string {
	if !strings.Contains(s, "://") {
		return s
	}
	return falakURLInText.ReplaceAllStringFunc(s, func(raw string) string {
		u, err := url.Parse(raw)
		if err != nil || u.Scheme == "" || u.Host == "" {
			return falakSafeRawURL(raw)
		}
		return falakSafeURL(u)
	})
}

// falakSafeRawURL makes a URL no parser accepts (a bad port, an empty host) safe all the same: everything up to the
// last "@" before the query is userinfo and dropped (a password may hold "@" or "/"), query and fragment go, the
// path is redacted.
func falakSafeRawURL(raw string) string {
	m := falakAbsolute.FindStringSubmatch(raw)
	if m == nil {
		p, _, _ := strings.Cut(raw, "?")
		p, _, _ = strings.Cut(p, "#")
		return falakRedactPath(p)
	}
	rest := m[2]
	if at := strings.LastIndex(rest, "@"); at >= 0 {
		rest = rest[at+1:]
	}
	host, path, ok := strings.Cut(rest, "/")
	if !ok {
		return m[1] + "://" + host + "/"
	}
	return m[1] + "://" + host + falakRedactPath("/"+path)
}

// ---- spans --------------------------------------------------------------------------------------------------------

const (
	falakInternal = 1
	falakServer   = 2
	falakClient   = 3
	falakError    = 2
)

type falakKV struct {
	Key   string         `json:"key"`
	Value map[string]any `json:"value"`
}

func falakStr(k, v string) falakKV { return falakKV{k, map[string]any{"stringValue": v}} }
func falakInt(k string, v int64) falakKV {
	return falakKV{k, map[string]any{"intValue": strconv.FormatInt(v, 10)}}
}
func falakBool(k string, v bool) falakKV { return falakKV{k, map[string]any{"boolValue": v}} }

type falakEvent struct {
	Name       string    `json:"name"`
	Time       string    `json:"timeUnixNano"`
	Attributes []falakKV `json:"attributes"`
}

type falakStatus struct {
	Code    int    `json:"code"`
	Message string `json:"message,omitempty"`
}

type falakSpan struct {
	mu           sync.Mutex
	TraceID      string       `json:"traceId"`
	SpanID       string       `json:"spanId"`
	ParentSpanID string       `json:"parentSpanId,omitempty"`
	Name         string       `json:"name"`
	Kind         int          `json:"kind"`
	Start        string       `json:"startTimeUnixNano"`
	End          string       `json:"endTimeUnixNano"`
	Attributes   []falakKV    `json:"attributes"`
	Events       []falakEvent `json:"events"`
	Status       *falakStatus `json:"status,omitempty"`
}

func falakHex(n int) string {
	b := make([]byte, n)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

func falakNanos() string { return strconv.FormatInt(time.Now().UnixNano(), 10) }

func falakNewSpan(name string, kind int, parent *falakSpan, attrs ...falakKV) *falakSpan {
	s := &falakSpan{TraceID: falakHex(16), SpanID: falakHex(8), Name: name, Kind: kind, Start: falakNanos(), Attributes: attrs, Events: []falakEvent{}}
	if parent != nil {
		s.TraceID, s.ParentSpanID = parent.TraceID, parent.SpanID
	}
	return s
}

func (s *falakSpan) attr(kv ...falakKV) {
	s.mu.Lock()
	s.Attributes = append(s.Attributes, kv...)
	s.mu.Unlock()
}

// exception adds an `exception` event; an unhandled one also sets the ERROR status.
func (s *falakSpan) exception(err error, handled bool) {
	typ, stack := fmt.Sprintf("%T", err), ""
	if typ == "*errors.errorString" || typ == "*fmt.wrapError" || typ == "*fmt.wrapErrors" {
		typ = "error" // errors.New / fmt.Errorf: the message says it all
	}
	var p *falakPanic
	if errors.As(err, &p) {
		typ, stack = "panic", string(p.stack)
		if e, ok := p.value.(error); ok {
			typ = "panic: " + fmt.Sprintf("%T", e)
		}
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	s.Events = append(s.Events, falakEvent{Name: "exception", Time: falakNanos(), Attributes: []falakKV{
		falakStr("exception.type", typ), falakStr("exception.message", falakCut(falakRedactText(err.Error()), 4096)),
		falakStr("exception.stacktrace", falakCut(falakRedactText(stack), 16384)), falakBool("falak.exception.handled", handled),
	}})
	if !handled {
		s.Status = &falakStatus{Code: falakError, Message: falakCut(falakRedactText(err.Error()), 512)}
	}
}

func falakCut(s string, n int) string {
	if len(s) > n {
		return s[:n]
	}
	return s
}

type falakSpanKey struct{}

func falakWithSpan(ctx context.Context, s *falakSpan) context.Context {
	return context.WithValue(ctx, falakSpanKey{}, s)
}

func falakSpanFrom(ctx context.Context) *falakSpan {
	s, _ := ctx.Value(falakSpanKey{}).(*falakSpan)
	return s
}

// ---- export -------------------------------------------------------------------------------------------------------

// falakExporter batches finished spans (every second, or 256 at a time) and posts them as OTLP/HTTP JSON to the
// function's socket. It never blocks a request: a full queue drops spans, a failed send drops the batch.
type falakExporter struct {
	enabled bool
	queue   chan *falakSpan
	client  *http.Client
	sendMu  sync.Mutex
	once    sync.Once
}

var falakTelemetry = func() *falakExporter {
	sock := os.Getenv("FALAK_OTLP_SOCKET")
	e := &falakExporter{queue: make(chan *falakSpan, 4096)}
	if sock == "" || os.Getenv("FALAK_TELEMETRY") == "off" {
		return e
	}
	if _, err := os.Stat(sock); err != nil {
		return e
	}
	e.enabled = true
	e.client = &http.Client{Timeout: 2 * time.Second, Transport: &http.Transport{
		DialContext: func(ctx context.Context, _, _ string) (net.Conn, error) {
			return (&net.Dialer{}).DialContext(ctx, "unix", sock)
		},
	}}
	return e
}()

func (e *falakExporter) finish(s *falakSpan) {
	if !e.enabled {
		return
	}
	s.mu.Lock()
	s.End = falakNanos()
	s.mu.Unlock()
	e.once.Do(func() { go e.loop() })
	select {
	case e.queue <- s:
	default: // agent down: drop rather than grow
	}
}

func (e *falakExporter) loop() {
	tick := time.NewTicker(time.Second)
	defer tick.Stop()
	for range tick.C {
		e.flush()
	}
}

// flush sends everything queued; after a failed send the rest is dropped (a shutdown must not outlast the grace
// period).
func (e *falakExporter) flush() {
	if !e.enabled {
		return
	}
	e.sendMu.Lock()
	defer e.sendMu.Unlock()
	for {
		batch := make([]*falakSpan, 0, 256)
	fill:
		for len(batch) < 256 {
			select {
			case s := <-e.queue:
				batch = append(batch, s)
			default:
				break fill
			}
		}
		if len(batch) == 0 {
			return
		}
		if !e.post(batch) {
			for {
				select {
				case <-e.queue:
				default:
					return
				}
			}
		}
	}
}

func (e *falakExporter) post(batch []*falakSpan) bool {
	for _, s := range batch {
		s.mu.Lock()
	}
	body, err := json.Marshal(map[string]any{"resourceSpans": []any{map[string]any{
		"resource": map[string]any{"attributes": []falakKV{
			falakStr("telemetry.sdk.name", "falak-fn"), falakStr("telemetry.sdk.language", "go"),
			falakStr("process.runtime.name", "go"), falakStr("process.runtime.version", runtime.Version()),
		}},
		"scopeSpans": []any{map[string]any{"scope": map[string]any{"name": "falak-fn-go"}, "spans": batch}},
	}}})
	for _, s := range batch {
		s.mu.Unlock()
	}
	if err != nil {
		return false
	}
	res, err := e.client.Post("http://falak/v1/traces", "application/json", bytes.NewReader(body))
	if err != nil {
		return false
	}
	res.Body.Close()
	return true
}
