// Code generated by Kiln (the Go function runtime). DO NOT EDIT.
//
// kiln-fn-install copies this file into the function's package (package main) next to a generated main(). It
// serves the function's Handler on $PORT, runs its Scheduled handler for `kiln-fn-run`, and reports telemetry to
// $KILN_OTLP_SOCKET following the Kiln telemetry contract (contracts/telemetry/README.md), encoded like the other
// runtimes: request spans named by the ServeMux pattern, panics, outgoing HTTP calls and scheduled runs. Standard
// library only. Identifiers starting with "kiln" and the Event type are reserved for it.

package main

import (
	"bufio"
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/signal"
	"regexp"
	"runtime"
	"runtime/debug"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"time"
)

// Event is what Scheduled receives: which schedule fired, and why.
type Event struct {
	// Name of the schedule ("Hourly").
	Name string `json:"name"`
	// Schedule is its key.
	Schedule string `json:"schedule"`
	// Cron is its expression ("@hourly", "*/5 * * * *").
	Cron string `json:"cron"`
	// Trigger is "cron", or "manual" for Run now.
	Trigger string `json:"trigger"`
	// ScheduledTime is when the run started.
	ScheduledTime time.Time `json:"scheduled_time"`
}

// kilnAdapt accepts what a function may export as Handler: an http.Handler (a *http.ServeMux, a router) or a
// func(http.ResponseWriter, *http.Request).
func kilnAdapt(h any) http.Handler {
	switch v := h.(type) {
	case http.Handler:
		return v
	case func(http.ResponseWriter, *http.Request):
		return http.HandlerFunc(v)
	}
	panic(fmt.Sprintf("kiln: Handler must be an http.Handler or a func(http.ResponseWriter, *http.Request), not %T", h))
}

// kilnMain is the generated main(): `run` runs Scheduled once, anything else serves Handler.
func kilnMain(handler http.Handler, scheduled func(context.Context, Event) error) {
	kilnInstrumentHTTP()
	if len(os.Args) > 1 && os.Args[1] == "run" {
		os.Exit(kilnRun(scheduled))
	}
	kilnServe(handler)
}

func kilnServe(handler http.Handler) {
	if handler == nil {
		handler = http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			http.Error(w, "this function has no Handler (it only runs on schedules)", http.StatusNotFound)
		})
	}
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
	srv := &http.Server{Addr: "0.0.0.0:" + port, Handler: kilnTrace(handler), ReadHeaderTimeout: 30 * time.Second}

	stop := make(chan os.Signal, 1)
	signal.Notify(stop, syscall.SIGTERM, syscall.SIGINT)
	done := make(chan struct{})
	go func() {
		<-stop
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		_ = srv.Shutdown(ctx)
		close(done)
	}()

	// Package init (the function's globals) has run: listening now means ready.
	if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
		fmt.Fprintln(os.Stderr, "kiln:", err)
		os.Exit(1)
	}
	<-done
	kilnTelemetry.flush()
}

func kilnRun(scheduled func(context.Context, Event) error) (code int) {
	name := os.Getenv("KILN_SCHEDULE_NAME")
	if name == "" {
		name = os.Getenv("KILN_SCHEDULE")
	}
	event := Event{Name: name, Schedule: os.Getenv("KILN_SCHEDULE"), Cron: os.Getenv("KILN_SCHEDULE_CRON"), Trigger: "cron", ScheduledTime: time.Now()}
	if os.Getenv("KILN_TRIGGER") == "manual" {
		event.Trigger = "manual"
	}
	if scheduled == nil {
		fmt.Fprintln(os.Stderr, "kiln: the function has no Scheduled handler: add `func Scheduled(ctx context.Context, event Event) error`")
		return 1
	}

	ctx, cancel := signal.NotifyContext(context.Background(), syscall.SIGTERM, syscall.SIGINT)
	defer cancel()
	cron := ""
	if event.Cron != "" {
		cron = ", " + event.Cron
	}
	fmt.Printf("kiln: running %s (%s%s)\n", name, event.Trigger, cron)
	span := kilnNewSpan("schedule "+name, kilnInternal, nil,
		kilnStr("kiln.event.type", "scheduled_task"), kilnStr("kiln.schedule.name", name), kilnStr("kiln.schedule.expression", event.Cron))
	started := time.Now()

	err := func() (err error) {
		defer func() {
			if v := recover(); v != nil {
				err = &kilnPanic{value: v, stack: debug.Stack()}
			}
		}()
		return scheduled(kilnWithSpan(ctx, span), event)
	}()

	if err != nil {
		code = 1
		fmt.Fprintf(os.Stderr, "kiln: %s failed: %v\n", name, err)
		var p *kilnPanic
		if errors.As(err, &p) {
			os.Stderr.Write(p.stack)
		}
		span.exception(err, false)
		span.attr(kilnStr("kiln.schedule.status", "failed"))
	} else {
		fmt.Printf("kiln: %s finished in %dms\n", name, time.Since(started).Milliseconds())
		span.attr(kilnStr("kiln.schedule.status", "finished"))
	}
	kilnTelemetry.finish(span)
	kilnTelemetry.flush()
	return code
}

// ---- requests -----------------------------------------------------------------------------------------------------

const kilnUnmatched = "(unmatched)"

var kilnSegment = regexp.MustCompile(`(?i)^\d+$|^[0-9a-f-]{16,}$|^[A-Za-z0-9_-]{24,}$`)

// kilnNormalize: /users/42 → /users/:id, for handlers without a ServeMux pattern.
func kilnNormalize(path string) string {
	segs := strings.Split(path, "/")
	for i, s := range segs {
		if kilnSegment.MatchString(s) {
			segs[i] = ":id"
		}
	}
	if out := strings.Join(segs, "/"); out != "" {
		return out
	}
	return "/"
}

// kilnRoute is the route template the ServeMux matched ("GET /users/{id}" → "/users/{id}", "GET /{$}" → "/"),
// else "".
func kilnRoute(pattern string) string {
	if i := strings.IndexByte(pattern, '/'); i >= 0 {
		return strings.TrimSuffix(pattern[i:], "{$}")
	}
	return ""
}

var kilnTraceparent = regexp.MustCompile(`^00-([0-9a-f]{32})-([0-9a-f]{16})-[0-9a-f]{2}$`)

// kilnTrace wraps the function's handler: one `request` span per request, panics recorded (answered with 500).
func kilnTrace(h http.Handler) http.Handler {
	_, isMux := h.(*http.ServeMux)
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !kilnTelemetry.enabled {
			kilnServeSafely(h, w, r, nil)
			return
		}
		span := kilnNewSpan(r.Method, kilnServer, nil,
			kilnStr("kiln.event.type", "request"), kilnStr("http.request.method", r.Method), kilnStr("url.path", kilnRedactPath(r.URL.Path)),
			kilnBool("faas.coldstart", r.Header.Get("X-Kiln-Cold-Start") == "1"))
		if m := kilnTraceparent.FindStringSubmatch(r.Header.Get("traceparent")); m != nil {
			span.TraceID, span.ParentSpanID = m[1], m[2]
		}
		rec := &kilnRecorder{ResponseWriter: w}
		req := r.WithContext(kilnWithSpan(r.Context(), span))
		kilnServeSafely(h, rec, req, span)

		route := kilnRoute(req.Pattern)
		switch {
		case route != "":
		case isMux:
			route = kilnUnmatched
		default:
			route = kilnRedactPath(kilnNormalize(r.URL.Path))
		}
		status := rec.status
		if status == 0 {
			status = http.StatusOK
		}
		span.Name = r.Method + " " + route
		span.attr(kilnStr("http.route", route), kilnInt("http.response.status_code", int64(status)))
		if status >= 500 && span.Status == nil {
			span.Status = &kilnStatus{Code: kilnError}
		}
		kilnTelemetry.finish(span)
	})
}

// kilnServeSafely turns a panic into a 500 (and an exception on the span) instead of a dropped connection.
func kilnServeSafely(h http.Handler, w http.ResponseWriter, r *http.Request, span *kilnSpan) {
	defer func() {
		v := recover()
		if v == nil {
			return
		}
		if v == http.ErrAbortHandler {
			panic(v)
		}
		p := &kilnPanic{value: v, stack: debug.Stack()}
		fmt.Fprintf(os.Stderr, "kiln: panic serving %s %s: %v\n%s", r.Method, r.URL.Path, v, p.stack)
		if span != nil {
			span.exception(p, false)
		}
		if rec, ok := w.(*kilnRecorder); !ok || rec.status == 0 {
			http.Error(w, "Internal Server Error", http.StatusInternalServerError)
		}
	}()
	h.ServeHTTP(w, r)
}

type kilnPanic struct {
	value any
	stack []byte
}

func (p *kilnPanic) Error() string { return fmt.Sprint(p.value) }

// kilnRecorder notes the status; Unwrap keeps http.ResponseController (flush, deadlines, hijack) working.
type kilnRecorder struct {
	http.ResponseWriter
	status int
}

func (r *kilnRecorder) WriteHeader(code int) {
	if r.status == 0 {
		r.status = code
	}
	r.ResponseWriter.WriteHeader(code)
}

func (r *kilnRecorder) Write(b []byte) (int, error) {
	if r.status == 0 {
		r.status = http.StatusOK
	}
	return r.ResponseWriter.Write(b)
}

func (r *kilnRecorder) Unwrap() http.ResponseWriter { return r.ResponseWriter }

// Flush, Hijack and ReadFrom pass through to the server's writer, so libraries that type-assert it (websockets,
// streaming, sendfile) work as without Kiln.
func (r *kilnRecorder) Flush() {
	if f, ok := r.ResponseWriter.(http.Flusher); ok {
		if r.status == 0 {
			r.status = http.StatusOK
		}
		f.Flush()
	}
}

func (r *kilnRecorder) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	h, ok := r.ResponseWriter.(http.Hijacker)
	if !ok {
		return nil, nil, http.ErrNotSupported
	}
	conn, rw, err := h.Hijack()
	if err == nil && r.status == 0 {
		r.status = http.StatusSwitchingProtocols
	}
	return conn, rw, err
}

func (r *kilnRecorder) ReadFrom(src io.Reader) (int64, error) {
	if r.status == 0 {
		r.status = http.StatusOK
	}
	if rf, ok := r.ResponseWriter.(io.ReaderFrom); ok {
		return rf.ReadFrom(src)
	}
	return io.Copy(struct{ io.Writer }{r.ResponseWriter}, src)
}

// ---- outgoing HTTP ------------------------------------------------------------------------------------------------

// kilnInstrumentHTTP traces http.DefaultClient (http.Get, http.Post, http.DefaultClient.Do). http.DefaultTransport
// itself stays an *http.Transport, so code that clones it (`http.DefaultTransport.(*http.Transport).Clone()`)
// keeps working; a client of your own is traced with `Transport: http.DefaultClient.Transport`.
func kilnInstrumentHTTP() {
	base := http.DefaultClient.Transport
	if base == nil {
		base = http.DefaultTransport
	}
	http.DefaultClient.Transport = &kilnTransport{base: base}
}

// kilnTransport records `outgoing_request` spans for calls made with a request's (or a run's) context:
// http.NewRequestWithContext(r.Context(), …) or the ctx Scheduled receives. No query strings or userinfo, and secret
// path segments are redacted (kilnRedactPath).
type kilnTransport struct{ base http.RoundTripper }

func (t *kilnTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	parent := kilnSpanFrom(req.Context())
	if parent == nil || !kilnTelemetry.enabled {
		return t.base.RoundTrip(req)
	}
	span := kilnNewSpan(req.Method+" "+req.URL.Host, kilnClient, parent,
		kilnStr("kiln.event.type", "outgoing_request"), kilnStr("http.request.method", req.Method),
		kilnStr("url.full", kilnSafeURL(req.URL)), kilnStr("server.address", req.URL.Hostname()))
	res, err := t.base.RoundTrip(req)
	if err != nil {
		span.exception(err, true)
		span.Status = &kilnStatus{Code: kilnError, Message: kilnCut(kilnRedactText(err.Error()), 512)}
	} else {
		span.attr(kilnInt("http.response.status_code", int64(res.StatusCode)))
		if res.StatusCode >= 500 {
			span.Status = &kilnStatus{Code: kilnError}
		}
	}
	kilnTelemetry.finish(span)
	return res, err
}

// ---- redaction ---------------------------------------------------------------------------------------------------

// Secrets in URL paths never reach telemetry: the same rules as the other runtimes (shared/redact.mjs) and the
// function gateway.
const kilnRedacted = "{redacted}"

var (
	kilnTelegram   = regexp.MustCompile(`^bot\d+:[A-Za-z0-9_-]+$`)
	kilnColonToken = regexp.MustCompile(`^[A-Za-z0-9_-]+:[A-Za-z0-9_-]{16,}$`)
	kilnLong       = regexp.MustCompile(`^[A-Za-z0-9_:-]{32,}$`)
	kilnMixed      = regexp.MustCompile(`^[A-Za-z0-9_-]{20,}$`)
)

func kilnRedactSegment(seg string) string {
	digit := strings.ContainsAny(seg, "0123456789")
	switch {
	case kilnTelegram.MatchString(seg):
		return "bot" + kilnRedacted
	case kilnColonToken.MatchString(seg), kilnLong.MatchString(seg) && digit:
		return kilnRedacted
	case kilnMixed.MatchString(seg) && digit && strings.ToLower(seg) != seg && strings.ToUpper(seg) != seg:
		return kilnRedacted
	}
	return seg
}

// kilnRedactPath: /bot123:AAE…/sendMessage → /bot{redacted}/sendMessage.
func kilnRedactPath(p string) string {
	segs := strings.Split(p, "/")
	for i, s := range segs {
		segs[i] = kilnRedactSegment(s)
	}
	return strings.Join(segs, "/")
}

// kilnSafeURL is scheme://host[:port]/path: no userinfo, no query, no fragment, secret segments redacted.
func kilnSafeURL(u *url.URL) string {
	p := u.EscapedPath()
	if p == "" {
		p = "/"
	}
	return u.Scheme + "://" + u.Host + kilnRedactPath(p)
}

var kilnURLInText = regexp.MustCompile(`[a-zA-Z][a-zA-Z0-9+.-]*://[^\s"'<>` + "`" + `]+`)

// kilnRedactText makes every URL a free text quotes safe (Go's errors quote the full request URL).
func kilnRedactText(s string) string {
	if !strings.Contains(s, "://") {
		return s
	}
	return kilnURLInText.ReplaceAllStringFunc(s, func(raw string) string {
		u, err := url.Parse(raw)
		if err != nil || u.Scheme == "" || u.Host == "" {
			p, _, _ := strings.Cut(raw, "?")
			return kilnRedactPath(p)
		}
		return kilnSafeURL(u)
	})
}

// ---- spans --------------------------------------------------------------------------------------------------------

const (
	kilnInternal = 1
	kilnServer   = 2
	kilnClient   = 3
	kilnError    = 2
)

type kilnKV struct {
	Key   string         `json:"key"`
	Value map[string]any `json:"value"`
}

func kilnStr(k, v string) kilnKV { return kilnKV{k, map[string]any{"stringValue": v}} }
func kilnInt(k string, v int64) kilnKV {
	return kilnKV{k, map[string]any{"intValue": strconv.FormatInt(v, 10)}}
}
func kilnBool(k string, v bool) kilnKV { return kilnKV{k, map[string]any{"boolValue": v}} }

type kilnEvent struct {
	Name       string   `json:"name"`
	Time       string   `json:"timeUnixNano"`
	Attributes []kilnKV `json:"attributes"`
}

type kilnStatus struct {
	Code    int    `json:"code"`
	Message string `json:"message,omitempty"`
}

type kilnSpan struct {
	mu           sync.Mutex
	TraceID      string      `json:"traceId"`
	SpanID       string      `json:"spanId"`
	ParentSpanID string      `json:"parentSpanId,omitempty"`
	Name         string      `json:"name"`
	Kind         int         `json:"kind"`
	Start        string      `json:"startTimeUnixNano"`
	End          string      `json:"endTimeUnixNano"`
	Attributes   []kilnKV    `json:"attributes"`
	Events       []kilnEvent `json:"events"`
	Status       *kilnStatus `json:"status,omitempty"`
}

func kilnHex(n int) string {
	b := make([]byte, n)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

func kilnNanos() string { return strconv.FormatInt(time.Now().UnixNano(), 10) }

func kilnNewSpan(name string, kind int, parent *kilnSpan, attrs ...kilnKV) *kilnSpan {
	s := &kilnSpan{TraceID: kilnHex(16), SpanID: kilnHex(8), Name: name, Kind: kind, Start: kilnNanos(), Attributes: attrs, Events: []kilnEvent{}}
	if parent != nil {
		s.TraceID, s.ParentSpanID = parent.TraceID, parent.SpanID
	}
	return s
}

func (s *kilnSpan) attr(kv ...kilnKV) {
	s.mu.Lock()
	s.Attributes = append(s.Attributes, kv...)
	s.mu.Unlock()
}

// exception adds an `exception` event; an unhandled one also sets the ERROR status.
func (s *kilnSpan) exception(err error, handled bool) {
	typ, stack := fmt.Sprintf("%T", err), ""
	if typ == "*errors.errorString" || typ == "*fmt.wrapError" || typ == "*fmt.wrapErrors" {
		typ = "error" // errors.New / fmt.Errorf: the message says it all
	}
	var p *kilnPanic
	if errors.As(err, &p) {
		typ, stack = "panic", string(p.stack)
		if e, ok := p.value.(error); ok {
			typ = "panic: " + fmt.Sprintf("%T", e)
		}
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	s.Events = append(s.Events, kilnEvent{Name: "exception", Time: kilnNanos(), Attributes: []kilnKV{
		kilnStr("exception.type", typ), kilnStr("exception.message", kilnCut(kilnRedactText(err.Error()), 4096)),
		kilnStr("exception.stacktrace", kilnCut(kilnRedactText(stack), 16384)), kilnBool("kiln.exception.handled", handled),
	}})
	if !handled {
		s.Status = &kilnStatus{Code: kilnError, Message: kilnCut(kilnRedactText(err.Error()), 512)}
	}
}

func kilnCut(s string, n int) string {
	if len(s) > n {
		return s[:n]
	}
	return s
}

type kilnSpanKey struct{}

func kilnWithSpan(ctx context.Context, s *kilnSpan) context.Context {
	return context.WithValue(ctx, kilnSpanKey{}, s)
}

func kilnSpanFrom(ctx context.Context) *kilnSpan {
	s, _ := ctx.Value(kilnSpanKey{}).(*kilnSpan)
	return s
}

// ---- export -------------------------------------------------------------------------------------------------------

// kilnExporter batches finished spans (every second, or 256 at a time) and posts them as OTLP/HTTP JSON to the
// function's socket. It never blocks a request: a full queue drops spans, a failed send drops the batch.
type kilnExporter struct {
	enabled bool
	queue   chan *kilnSpan
	client  *http.Client
	sendMu  sync.Mutex
	once    sync.Once
}

var kilnTelemetry = func() *kilnExporter {
	sock := os.Getenv("KILN_OTLP_SOCKET")
	e := &kilnExporter{queue: make(chan *kilnSpan, 4096)}
	if sock == "" || os.Getenv("KILN_TELEMETRY") == "off" {
		return e
	}
	if _, err := os.Stat(sock); err != nil {
		return e
	}
	e.enabled = true
	e.client = &http.Client{Timeout: 2 * time.Second, Transport: &http.Transport{
		DialContext: func(ctx context.Context, _, _ string) (net.Conn, error) {
			return (&net.Dialer{}).DialContext(ctx, "unix", sock)
		},
	}}
	return e
}()

func (e *kilnExporter) finish(s *kilnSpan) {
	if !e.enabled {
		return
	}
	s.mu.Lock()
	s.End = kilnNanos()
	s.mu.Unlock()
	e.once.Do(func() { go e.loop() })
	select {
	case e.queue <- s:
	default: // agent down: drop rather than grow
	}
}

func (e *kilnExporter) loop() {
	tick := time.NewTicker(time.Second)
	defer tick.Stop()
	for range tick.C {
		e.flush()
	}
}

// flush sends everything queued; after a failed send the rest is dropped (a shutdown must not outlast the grace
// period).
func (e *kilnExporter) flush() {
	if !e.enabled {
		return
	}
	e.sendMu.Lock()
	defer e.sendMu.Unlock()
	for {
		batch := make([]*kilnSpan, 0, 256)
	fill:
		for len(batch) < 256 {
			select {
			case s := <-e.queue:
				batch = append(batch, s)
			default:
				break fill
			}
		}
		if len(batch) == 0 {
			return
		}
		if !e.post(batch) {
			for {
				select {
				case <-e.queue:
				default:
					return
				}
			}
		}
	}
}

func (e *kilnExporter) post(batch []*kilnSpan) bool {
	for _, s := range batch {
		s.mu.Lock()
	}
	body, err := json.Marshal(map[string]any{"resourceSpans": []any{map[string]any{
		"resource": map[string]any{"attributes": []kilnKV{
			kilnStr("telemetry.sdk.name", "kiln-fn"), kilnStr("telemetry.sdk.language", "go"),
			kilnStr("process.runtime.name", "go"), kilnStr("process.runtime.version", runtime.Version()),
		}},
		"scopeSpans": []any{map[string]any{"scope": map[string]any{"name": "kiln-fn-go"}, "spans": batch}},
	}}})
	for _, s := range batch {
		s.mu.Unlock()
	}
	if err != nil {
		return false
	}
	res, err := e.client.Post("http://kiln/v1/traces", "application/json", bytes.NewReader(body))
	if err != nil {
		return false
	}
	res.Body.Close()
	return true
}
