package builder

import (
	"fmt"
	"strings"
)

const generatedDockerignore = ".git\nnode_modules\n.env\n.env.*\n!.env.example\nvendor\n.DS_Store\n"

// GenerateDockerfile renders a Dockerfile for a detected plan (used when the repo has none and
// Railpack is unavailable). Images listen on plan.Port.
func GenerateDockerfile(p Plan) (string, error) {
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }
	shellJoin := func(c []string) string { return strings.Join(c, " ") }
	nodeImage := "node:" + firstNonEmpty(p.NodeVersion, "22") + "-slim"
	assetsImage := nodeImage
	if p.PackageManager == "bun" {
		assetsImage = "oven/bun:" + firstNonEmpty(p.BunVersion, "1")
	}
	corepack := p.PackageManager == "pnpm" || p.PackageManager == "yarn"
	jsSteps := func() {
		if corepack {
			w("RUN corepack enable")
		}
		for _, s := range p.Steps {
			if s.Cmd[0] == "composer" {
				continue
			}
			pre := ""
			if len(s.PreClean) > 0 {
				pre = "rm -rf " + strings.Join(s.PreClean, " ") + " && "
			}
			env := ""
			if len(s.Env) > 0 {
				env = strings.Join(s.Env, " ") + " "
			}
			w("RUN %s%s%s", pre, env, shellJoin(s.Cmd))
		}
	}
	w("# syntax=docker/dockerfile:1")
	w("# Generated by kiln-builder for %s", firstNonEmpty(p.Framework, p.Provider))
	switch p.Runtime {
	case "php":
		hasAssets := p.PackageManager != ""
		if hasAssets {
			w("FROM %s AS assets", assetsImage)
			w("WORKDIR /app")
			w("COPY . .")
			jsSteps()
			w("")
		}
		w("FROM dunglas/frankenphp:1-php%s", firstNonEmpty(p.PHPVersion, "8.4"))
		w("RUN install-php-extensions pdo_mysql pdo_pgsql redis intl zip bcmath pcntl opcache")
		w("COPY --from=composer:2 /usr/bin/composer /usr/bin/composer")
		w("WORKDIR /app")
		w("COPY . .")
		if hasAssets {
			w("COPY --from=assets /app/public /app/public")
		}
		w("RUN composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist --no-progress")
		if p.Provider == "laravel" {
			w("RUN chown -R www-data:www-data storage bootstrap/cache")
		}
		w("ENV SERVER_NAME=:%d", p.Port)
		w("EXPOSE %d", p.Port)
	case "node", "bun":
		img := nodeImage
		if p.Runtime == "bun" {
			img = "oven/bun:" + firstNonEmpty(p.BunVersion, "1")
		}
		w("FROM %s", img)
		w("WORKDIR /app")
		w("COPY . .")
		jsSteps()
		w("ENV NODE_ENV=production PORT=%d HOST=0.0.0.0", p.Port)
		w("EXPOSE %d", p.Port)
		if p.StartCommand == "" {
			return "", fmt.Errorf("no start command detected for %s app; add a Dockerfile or a start script", p.Runtime)
		}
		w("CMD [\"sh\", \"-c\", %q]", p.StartCommand)
	case "deno":
		w("FROM denoland/deno:%s", firstNonEmpty(p.DenoVersion, "2"))
		w("WORKDIR /app")
		w("COPY . .")
		for _, s := range p.Steps {
			w("RUN %s", shellJoin(s.Cmd))
		}
		w("ENV PORT=%d", p.Port)
		w("EXPOSE %d", p.Port)
		if p.StartCommand == "" {
			return "", fmt.Errorf("no start command detected for deno app")
		}
		w("CMD [\"sh\", \"-c\", %q]", p.StartCommand)
	case "static":
		src := "/app"
		if len(p.Steps) > 0 {
			w("FROM %s AS build", assetsImage)
			w("WORKDIR /app")
			w("COPY . .")
			jsSteps()
			w("")
		}
		w("FROM caddy:2-alpine")
		if len(p.Steps) > 0 {
			w("COPY --from=build %s/%s /srv", src, strings.TrimPrefix(p.OutputDir, "/"))
		} else {
			w("COPY %s /srv", firstNonEmpty(p.OutputDir, "."))
		}
		w("EXPOSE %d", p.Port)
		w("CMD [\"caddy\", \"file-server\", \"--root\", \"/srv\", \"--listen\", \":%d\"]", p.Port)
	default:
		return "", fmt.Errorf("cannot generate a Dockerfile for runtime %q", p.Runtime)
	}
	return b.String(), nil
}
