package builder

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"
)

// Server polls the control plane for build jobs and runs them one at a time.
type Server struct {
	URL     string // control-plane base URL
	Token   string // builder token
	Name    string // builder name (reported to the control plane)
	Wait    int    // long-poll seconds
	HTTP    *http.Client
	Builder *Builder
	Log     *slog.Logger
	// Once stops after one job (tests, cron-style runs).
	Once bool
	// Idle is the pause after an empty poll when Wait is 0 (no long-poll). Default 5s.
	Idle time.Duration
	// RunID identifies this process to the control plane (new per start; generated by Run when empty).
	RunID string
	// HeartbeatInterval between heartbeats while a build runs (default 20s; the control plane fails a build after
	// 90s of silence).
	HeartbeatInterval time.Duration
}

// NewRunID returns a random run id.
func NewRunID() string {
	b := make([]byte, 12)
	_, _ = rand.Read(b)
	return "run-" + hex.EncodeToString(b)
}

// ErrNoJob is returned by Next when the queue is empty.
var ErrNoJob = errors.New("no build job queued")

// Next long-polls PathNextBuild.
func (s *Server) Next(ctx context.Context) (Job, error) {
	q := url.Values{"wait": {strconv.Itoa(s.Wait)}}
	if s.Name != "" {
		q.Set("builder", s.Name)
	}
	if s.RunID != "" {
		q.Set("run", s.RunID)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, strings.TrimRight(s.URL, "/")+PathNextBuild+"?"+q.Encode(), nil)
	if err != nil {
		return Job{}, err
	}
	req.Header.Set("Authorization", "Bearer "+s.Token)
	req.Header.Set("Accept", "application/json")
	resp, err := s.HTTP.Do(req)
	if err != nil {
		return Job{}, err
	}
	defer resp.Body.Close()
	switch resp.StatusCode {
	case http.StatusNoContent:
		return Job{}, ErrNoJob
	case http.StatusOK:
	default:
		b, _ := io.ReadAll(io.LimitReader(resp.Body, 512))
		return Job{}, fmt.Errorf("GET %s: HTTP %d: %s", PathNextBuild, resp.StatusCode, strings.TrimSpace(string(b)))
	}
	// Accept both a bare job and a {"data": job} envelope (Laravel resources).
	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return Job{}, err
	}
	var env struct {
		Data json.RawMessage `json:"data"`
	}
	if json.Unmarshal(raw, &env) == nil && len(env.Data) > 0 {
		raw = env.Data
	}
	var j Job
	if err := json.Unmarshal(raw, &j); err != nil {
		return Job{}, fmt.Errorf("decode job: %w", err)
	}
	return j, nil
}

// Run loops until ctx is cancelled.
func (s *Server) Run(ctx context.Context) error {
	if s.HTTP == nil {
		s.HTTP = &http.Client{Timeout: time.Duration(s.Wait+30) * time.Second}
	}
	if s.Log == nil {
		s.Log = slog.New(slog.NewTextHandler(io.Discard, nil))
	}
	if s.Idle <= 0 {
		s.Idle = 5 * time.Second
	}
	if s.RunID == "" {
		s.RunID = NewRunID()
	}
	s.Log.Info("builder polling", "name", s.Name, "run_id", s.RunID)
	backoff := time.Second
	for ctx.Err() == nil {
		j, err := s.Next(ctx)
		switch {
		case errors.Is(err, ErrNoJob):
			backoff = time.Second
			if s.Wait == 0 {
				sleep(ctx, s.Idle)
			}
			continue
		case err != nil:
			if ctx.Err() != nil {
				return nil
			}
			s.Log.Warn("poll builds", "err", err, "retry_in", backoff)
			sleep(ctx, backoff)
			backoff = min(backoff*2, time.Minute)
			continue
		}
		backoff = time.Second
		s.runJob(ctx, j)
		if s.Once {
			return nil
		}
	}
	return nil
}

func (s *Server) runJob(ctx context.Context, j Job) {
	id := j.ID
	if id == "" {
		id = "invalid"
	}
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()
	sink := (&HTTPSink{URL: strings.TrimRight(s.URL, "/") + EventsPath(id), Token: s.Token, Client: s.HTTP, Log: s.Log, OnGone: cancel}).Start()
	s.Log.Info("build started", "build_id", id, "mode", j.Mode)
	hbCtx, stopHeartbeat := context.WithCancel(ctx)
	go s.heartbeat(hbCtx, id, cancel)
	res, err := s.Builder.Build(ctx, j, sink)
	stopHeartbeat()
	cctx, cancelFlush := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancelFlush()
	if ferr := sink.Close(cctx); ferr != nil {
		s.Log.Error("deliver build events", "build_id", id, "err", ferr)
	}
	if err != nil {
		s.Log.Error("build failed", "build_id", id, "err", err)
		return
	}
	s.Log.Info("build finished", "build_id", id, "duration_ms", res.DurationMS)
}

// heartbeat tells the control plane the build is alive until ctx ends; a 410 answer (the build is over there) aborts
// it through abort.
func (s *Server) heartbeat(ctx context.Context, id string, abort func()) {
	every := s.HeartbeatInterval
	if every <= 0 {
		every = 20 * time.Second
	}
	u := strings.TrimRight(s.URL, "/") + HeartbeatPath(id)
	for {
		req, err := http.NewRequestWithContext(ctx, http.MethodPost, u, nil)
		if err != nil {
			return
		}
		req.Header.Set("Authorization", "Bearer "+s.Token)
		req.Header.Set("Accept", "application/json")
		if resp, err := s.HTTP.Do(req); err == nil {
			_, _ = io.Copy(io.Discard, io.LimitReader(resp.Body, 4096))
			resp.Body.Close()
			if resp.StatusCode == http.StatusGone {
				s.Log.Warn("build ended on the control plane, aborting", "build_id", id)
				abort()
				return
			}
		} else if ctx.Err() == nil {
			s.Log.Debug("build heartbeat", "build_id", id, "err", err)
		}
		select {
		case <-ctx.Done():
			return
		case <-time.After(every):
		}
	}
}

func sleep(ctx context.Context, d time.Duration) {
	select {
	case <-ctx.Done():
	case <-time.After(d):
	}
}
