<?php

namespace Kiln\Network\Domain\Enums;

enum KeyStatus: string
{
    /** Generated by the control plane, delivery to the host pending. */
    case Pending = 'pending';
    /** Written to /etc/kiln/wireguard/<iface>.key; the control plane no longer holds the private key. */
    case Installed = 'installed';
    case Failed = 'failed';
}
