<?php

namespace Kiln\Fleet\Infrastructure;

/**
 * Renders the POSIX sh installer served at GET /install/{token}:
 * detect arch → download kiln-agent (checksum-verified when known) → enroll → `kiln-agent install` (systemd unit).
 */
final class InstallScript
{
    public const ARCHES = ['amd64', 'arm64'];

    /**
     * @param  array<string, string>  $checksums  arch => sha256 (optional)
     */
    public function __construct(
        private readonly PanelUrls $urls,
        private readonly AgentBinaries $binaries,
        private readonly array $checksums = [],
    ) {}

    public function render(string $token): string
    {
        $panel = self::quote($this->urls->panel());
        $tokenArg = self::quote($token);
        // The download URL is double-quoted so ${ARCH} expands; everything else is literal.
        $download = str_replace(['\\', '"', '`', '$('], ['\\\\', '\\"', '\\`', '\\$('], $this->urls->agentDownloadTemplate());
        $sumAmd64 = self::quote($this->checksum('amd64'));
        $sumArm64 = self::quote($this->checksum('arm64'));

        return <<<SH
#!/bin/sh
# kiln-agent installer — generated by the Kiln control plane.
# Installs /usr/local/bin/kiln-agent, enrolls this host with a one-time token and starts the service.
set -eu

KILN_PANEL_URL={$panel}
KILN_TOKEN={$tokenArg}
BIN=/usr/local/bin/kiln-agent

say() { printf 'kiln: %s\\n' "\$*"; }
fail() { printf 'kiln: error: %s\\n' "\$*" >&2; exit 1; }

[ "\$(id -u)" -eq 0 ] || fail "run as root (curl ... | sudo sh)"
command -v systemctl >/dev/null 2>&1 || fail "systemd is required"

case "\$(uname -s)" in
    Linux) ;;
    *) fail "unsupported OS: \$(uname -s)" ;;
esac

case "\$(uname -m)" in
    x86_64 | amd64) ARCH=amd64 ;;
    aarch64 | arm64) ARCH=arm64 ;;
    *) fail "unsupported architecture: \$(uname -m)" ;;
esac

if [ -r /etc/os-release ]; then
    . /etc/os-release
    [ "\${ID:-}" = "ubuntu" ] || say "warning: only Ubuntu LTS is supported (found \${ID:-unknown})"
fi

case "\$ARCH" in
    amd64) SHA256={$sumAmd64} ;;
    arm64) SHA256={$sumArm64} ;;
esac

URL="{$download}"
TMP="\$(mktemp)"
trap 'rm -f "\$TMP"' EXIT INT TERM

say "downloading kiln-agent (\$ARCH)"
if command -v curl >/dev/null 2>&1; then
    curl -fsSL --retry 5 --retry-delay 2 -o "\$TMP" "\$URL" || fail "download failed: \$URL"
elif command -v wget >/dev/null 2>&1; then
    wget -q -O "\$TMP" "\$URL" || fail "download failed: \$URL"
else
    fail "curl or wget is required"
fi

if [ -n "\$SHA256" ]; then
    echo "\$SHA256  \$TMP" | sha256sum -c - >/dev/null 2>&1 || fail "checksum mismatch for \$URL"
fi

install -m 0755 "\$TMP" "\$BIN"

say "enrolling with \$KILN_PANEL_URL"
"\$BIN" enroll --panel "\$KILN_PANEL_URL" --token "\$KILN_TOKEN" || fail "enrollment failed"

# The agent owns its systemd unit (kiln-agent install writes it, enables and starts the service).
"\$BIN" install || fail "service installation failed"

say "kiln-agent installed and running"

SH;
    }

    private function checksum(string $arch): string
    {
        return $this->checksums[$arch] ?? ($this->urls->isLocalDownload() ? (string) $this->binaries->checksum($arch) : '');
    }

    /** Single-quote for POSIX sh. */
    public static function quote(string $value): string
    {
        return "'".str_replace("'", "'\\''", $value)."'";
    }
}
