<?php

namespace Kiln\Fleet\Infrastructure;

/**
 * Renders the POSIX sh installer served at GET /install/{token}:
 * preflight (root, systemd, arch, OS, panel + agent API reachable, clock) → download kiln-agent (checksum-verified
 * when known) → stop a running agent → enroll (replacing an earlier identity) → `kiln-agent install` (systemd
 * unit) → `kiln-agent check` until the agent is connected.
 */
final class InstallScript
{
    public const ARCHES = ['amd64', 'arm64'];

    /** Seconds of clock difference to the panel above which the install stops (certificates are time-sensitive). */
    public const MAX_CLOCK_SKEW = 300;

    /**
     * @param  array<string, string>  $checksums  arch => sha256 (optional)
     */
    public function __construct(
        private readonly PanelUrls $urls,
        private readonly AgentBinaries $binaries,
        private readonly array $checksums = [],
    ) {}

    public function render(string $token): string
    {
        $panel = self::quote($this->urls->panel());
        $agentApi = self::quote($this->urls->agentApi());
        $tokenArg = self::quote($token);
        // The download URL is double-quoted so ${ARCH} expands; everything else is literal.
        $download = str_replace(['\\', '"', '`', '$('], ['\\\\', '\\"', '\\`', '\\$('], $this->urls->agentDownloadTemplate());
        $sumAmd64 = self::quote($this->checksum('amd64'));
        $sumArm64 = self::quote($this->checksum('arm64'));
        $maxSkew = self::MAX_CLOCK_SKEW;

        return <<<SH
#!/bin/sh
# kiln-agent installer — generated by the Kiln control plane.
# Installs /usr/local/bin/kiln-agent, enrolls this host with a one-time token and starts the service.
set -eu

KILN_PANEL_URL={$panel}
KILN_AGENT_API={$agentApi}
KILN_TOKEN={$tokenArg}
BIN=/usr/local/bin/kiln-agent

say() { printf 'kiln: %s\\n' "\$*"; }
warn() { printf 'kiln: warning: %s\\n' "\$*" >&2; }
fail() { printf 'kiln: error: %s\\n' "\$*" >&2; exit 1; }

[ "\$(id -u)" -eq 0 ] || fail "run as root (curl ... | sudo sh)"
command -v systemctl >/dev/null 2>&1 || fail "systemd is required"

case "\$(uname -s)" in
    Linux) ;;
    *) fail "unsupported OS: \$(uname -s)" ;;
esac

case "\$(uname -m)" in
    x86_64 | amd64) ARCH=amd64 ;;
    aarch64 | arm64) ARCH=arm64 ;;
    *) fail "unsupported architecture: \$(uname -m)" ;;
esac

# Distribution. Supported: Ubuntu 22.04, 24.04 and 26.04; other apt-based systems install with a warning.
OS_ID=unknown OS_VERSION='' OS_CODENAME=''
# shellcheck disable=SC1091
if [ -r /etc/os-release ]; then
    OS_ID="\$(. /etc/os-release && printf '%s' "\${ID:-unknown}")"
    OS_VERSION="\$(. /etc/os-release && printf '%s' "\${VERSION_ID:-}")"
    OS_CODENAME="\$(. /etc/os-release && printf '%s' "\${VERSION_CODENAME:-}")"
fi
say "OS: \$OS_ID \$OS_VERSION (\${OS_CODENAME:-no codename}), \$ARCH"
command -v apt-get >/dev/null 2>&1 || fail "Kiln manages servers with apt: use Ubuntu 22.04, 24.04 or 26.04"
case "\$OS_ID:\$OS_VERSION" in
    ubuntu:22.04 | ubuntu:24.04) ;;
    ubuntu:26.04) say "note: on Ubuntu 26.04 PHP comes from Ubuntu's own archive, which has only PHP 8.5" ;;
    ubuntu:* | debian:*) warn "\$OS_ID \$OS_VERSION is not supported (supported: Ubuntu 22.04, 24.04, 26.04); continuing" ;;
    *) warn "\$OS_ID is not supported (supported: Ubuntu 22.04, 24.04, 26.04); continuing" ;;
esac

case "\$ARCH" in
    amd64) SHA256={$sumAmd64} ;;
    arm64) SHA256={$sumArm64} ;;
esac

URL="{$download}"
TMP="\$(mktemp)"
PROBE="\$(mktemp)"
trap 'rm -f "\$TMP" "\$PROBE"' EXIT INT TERM

# Reachability and clock, before anything changes on this machine.
if command -v curl >/dev/null 2>&1; then
    HEADERS="\$(curl -sS -I --max-time 15 "\$KILN_PANEL_URL/" 2>"\$PROBE")" || fail "cannot reach the panel at \$KILN_PANEL_URL: \$(cat "\$PROBE")"
    # The agent API uses the private Kiln Fleet CA (-k: only connectivity is tested here) and answers 401 without
    # a client certificate.
    API_CODE="\$(curl -sSk -o /dev/null -w '%{http_code}' --max-time 15 "\$KILN_AGENT_API/ping" 2>"\$PROBE")" ||
        fail "cannot reach the agent API at \$KILN_AGENT_API: \$(cat "\$PROBE") (allow outbound HTTPS to it)"
    [ "\$API_CODE" = 401 ] || warn "the agent API at \$KILN_AGENT_API answered HTTP \$API_CODE without a client certificate (expected 401)"

    PANEL_DATE="\$(printf '%s\\n' "\$HEADERS" | tr -d '\\r' | sed -n 's/^[Dd][Aa][Tt][Ee]: *//p' | head -n 1)"
    if [ -n "\$PANEL_DATE" ] && PANEL_TS="\$(date -u -d "\$PANEL_DATE" +%s 2>/dev/null)"; then
        SKEW=\$((\$(date -u +%s) - PANEL_TS))
        if [ "\$SKEW" -lt 0 ]; then SKEW=\$((0 - SKEW)); fi
        if [ "\$SKEW" -gt {$maxSkew} ]; then
            fail "this machine's clock is \${SKEW}s off the panel's (\$(date -u '+%Y-%m-%d %H:%M:%S') UTC here, \$PANEL_DATE there); agent certificates depend on the time: fix it (timedatectl set-ntp true) and run the install command again"
        elif [ "\$SKEW" -gt 60 ]; then
            warn "this machine's clock is \${SKEW}s off the panel's; enable time sync (timedatectl set-ntp true)"
        fi
    fi
else
    warn "curl not found: skipping the reachability and clock checks"
fi

if [ -f /etc/kiln/agent.json ]; then
    OLD_AGENT="\$(sed -n 's/.*"agent_id": *"\\([^"]*\\)".*/\\1/p' /etc/kiln/agent.json | head -n 1)"
    say "this machine is already enrolled (agent \${OLD_AGENT:-unknown}); the new identity replaces it, the old one is backed up in /etc/kiln/previous/"
fi

say "downloading kiln-agent (\$ARCH)"
if command -v curl >/dev/null 2>&1; then
    curl -fsSL --retry 5 --retry-delay 2 -o "\$TMP" "\$URL" || fail "download failed: \$URL"
elif command -v wget >/dev/null 2>&1; then
    wget -q -O "\$TMP" "\$URL" || fail "download failed: \$URL"
else
    fail "curl or wget is required"
fi

if [ -n "\$SHA256" ]; then
    echo "\$SHA256  \$TMP" | sha256sum -c - >/dev/null 2>&1 || fail "checksum mismatch for \$URL"
fi

# A running agent (an earlier install) must not race the new identity; `kiln-agent install` starts it again.
WAS_RUNNING=0
if systemctl is-active --quiet kiln-agent 2>/dev/null; then
    say "stopping the running kiln-agent"
    systemctl stop kiln-agent || fail "could not stop kiln-agent"
    WAS_RUNNING=1
fi

install -m 0755 "\$TMP" "\$BIN"

say "enrolling with \$KILN_PANEL_URL"
if ! "\$BIN" enroll --panel "\$KILN_PANEL_URL" --token "\$KILN_TOKEN"; then
    if [ "\$WAS_RUNNING" = 1 ]; then systemctl start kiln-agent || true; fi
    fail "enrollment failed"
fi

# The agent owns its systemd unit (kiln-agent install writes it, enables and starts the service).
"\$BIN" install || fail "service installation failed"

say "waiting for kiln-agent to connect"
CONNECTED="\$("\$BIN" check --wait 60s)" || fail "kiln-agent is installed but not connected (reason above); logs: journalctl -u kiln-agent"
say "\$CONNECTED"

SH;
    }

    private function checksum(string $arch): string
    {
        return $this->checksums[$arch] ?? ($this->urls->isLocalDownload() ? (string) $this->binaries->checksum($arch) : '');
    }

    /** Single-quote for POSIX sh. */
    public static function quote(string $value): string
    {
        return "'".str_replace("'", "'\\''", $value)."'";
    }
}
